### ISSUE TITLE
Missing Strings - all languages

### ISSUE THREAD

**Issue by brianteeman** [hr-it-solutions/DD_J_com_gmaps_locations#76]
These strings are in : JROOT\administrator\language\en-GB\en-GB.com_content.ini which is not loaded in the view

COM_CONTENT_FILTER_SEARCH_DESC="CONTENT FILTER SEARCH DESC"
COM_CONTENT_FILTER_SEARCH_LABEL="CONTENT FILTER SEARCH LABEL"
COM_CONTENT_MODIFIED_ASC="CONTENT MODIFIED ASC"
COM_CONTENT_MODIFIED_DESC="CONTENT MODIFIED DESC"
COM_CONTENT_PUBLISH_DOWN_ASC="CONTENT PUBLISH DOWN ASC"
COM_CONTENT_PUBLISH_DOWN_DESC="CONTENT PUBLISH DOWN DESC"
COM_CONTENT_PUBLISH_UP_ASC="CONTENT PUBLISH UP ASC"
COM_CONTENT_PUBLISH_UP_DESC="CONTENT PUBLISH UP DESC"

<img width="256" alt="screenshotr11-25-11" src="https://user-images.githubusercontent.com/1296369/35218538-f148f152-ff66-11e7-9dd3-05b6a88b8e5f.png">

**Comment by Didldu-Florian** [comment]
Hmm, which view is it?

**Comment by brianteeman** [comment]
?option=com_dd_gmaps_locations&view=locations

**Comment by Didldu-Florian** [comment]
Can not reproduce the issue:
![backreport](https://user-images.githubusercontent.com/12803406/35220891-6d4f7512-ff78-11e7-8a6c-72af4a8aa62a.jpg)

Current dev branche semms working.

Try install current dev branche
https://github.com/Didldu-Florian/DD_J_com_gmaps_locations/tree/6d400d0749aaa24d025748ef4bfb5901f4b9b847

Update soon.

**Comment by brianteeman** [comment]
OK will test after lunch

**Comment by brianteeman** [comment]
You are looking in the wrong place. Its the sort fields as defined here 
https://github.com/hr-it-solutions/DD_J_com_gmaps_locations/blob/a7a680a57992c10b37b6df357b7e4ab8202875c6/admin/models/forms/filter_locations.xml#L99

![dd gmaps locations locations sample administration](https://user-images.githubusercontent.com/1296369/35222958-b4578d88-ff77-11e7-9d52-ab9df3f74624.png)
