### ISSUE TITLE
BUG - notice on save

### ISSUE THREAD

**Issue by brianteeman** [hr-it-solutions/DD_J_com_gmaps_locations#78]
If you havent entered the required fields for a contact then you correctly get the warning about the required fields being missing. However you also get a php notice
`Notice: Trying to get property 'll_c' of non-object in C:\Apache24\htdocs\cms\administrator\components\com_dd_gmaps_locations\models\location.php on line 283
`

<img width="793" alt="screenshotr12-01-42" src="https://user-images.githubusercontent.com/1296369/35219827-0a0acf6c-ff6c-11e7-85fa-48e2c77f97f4.png">

**Comment by Didldu-Florian** [comment]
Current dev branche semms working.

Try install current dev branche
https://github.com/Didldu-Florian/DD_J_com_gmaps_locations/tree/6d400d0749aaa24d025748ef4bfb5901f4b9b847

Update soon.

**Comment by brianteeman** [comment]
ok - will do after lunch - thanks

**Comment by brianteeman** [comment]
all good in dev
