### ISSUE TITLE
Category View

### ISSUE THREAD

**Issue by brianteeman** [hr-it-solutions/DD_J_com_gmaps_locations#81]
Before I dig into the code I was wondering if anyone had done a category view or something similar.

I have 8 categories, each with a description and image, and I am planning to have a view with all of them on one page - the user then selects the category and just sees the locations in that category

**Comment by Didldu-Florian** [comment]
Mhh, you are right that is currently missing. 
But it's easy to implement in the locations view. I'll add this feature next.

**Comment by Didldu-Florian** [comment]
Feature added to dev branche and will be implemented to our next release.
You will find the category list otions and a category desc setting at the menu params. 

If you use our filterbar, please update it also from the filterbar dev branche: https://github.com/hr-it-solutions/DD_J_mod_gmaps_locations_searchfilter/tree/dev

**Comment by brianteeman** [comment]
Either I did something wrong, I didnt explain something, or this isnt working

I think I have set it up correctly (see screenshots) but I just get No Results Found

<img width="639" alt="screenshotr14-19-13" src="https://user-images.githubusercontent.com/1296369/35392845-0794bfc4-01db-11e8-9ef5-14c9b505406f.png">
<img width="472" alt="screenshotr14-19-29" src="https://user-images.githubusercontent.com/1296369/35392846-07b5208e-01db-11e8-8a19-b183ae81c28b.png">
<img width="592" alt="screenshotr14-19-42" src="https://user-images.githubusercontent.com/1296369/35392847-07d45b48-01db-11e8-9282-656629fdc155.png">

**Comment by Didldu-Florian** [comment]
It did currently not include child categories.
Will implement this also.

**Comment by brianteeman** [comment]
To be clear - what I am trying to replicate is this https://www.reformjudaism.org.uk/synagogues/

**Comment by Didldu-Florian** [comment]
Should now work. Hope that's it.

**Comment by brianteeman** [comment]
We are clearly not talking about creating the same thing.

You are creating the ability to show the category description on the locations view. This works ok when there is only one category displayed on the page. (You dont show the category title but thats a different issue) but when you now display multiple categories on the view (by selecting a parent) then only the description of the first category is displayed. - this makes sense because of the logic so you can remove that last change you made as it doesnt help anyone.

What I was trying to do was this and it will need a new view 

### Category View
 
![the movement for reform judaism reform synagogues](https://user-images.githubusercontent.com/1296369/35406106-edab077e-01ff-11e8-8c78-441b4bbecee6.png)



RED = Category
BLUE = Category Image
Yellow = Category Description 

Then when you select one of those categories you get the regular locations view for a single category.

(I can create it manually with com_content for this page and manual links to the location menu items so if you dont think its worth creating then thats fine).

**Comment by brianteeman** [comment]
PS Thanks for your help in trying to create thiis for me and for responding so quickly!!!

**Comment by Didldu-Florian** [comment]
Mhh, now that's clear. Thanks for describing this. That's no problem. 
I will add this also next. I'll be glad to get your feedback and to help you ;)

**Comment by brianteeman** [comment]
I have a few other ideas where there can be improvement
1. Option to never use the "new" flag 
2. Use custom styled googlemaps - I was thinking of the 6 defaults offered by google here https://mapstyle.withgoogle.com/

**Comment by Didldu-Florian** [comment]
Categories view is now added to dev branche. Merge is still pending.
For the routing is helpwanted, this could still take some time.
Anyway, the categories view should now work by adding a form workaround insted of JRoute.

PS: Thanks for your two other features requestes.
The first one is no problem, the other one I will check ;)

**Comment by brianteeman** [comment]
Awesome

Sorry I cant help you on routing as that has always been a mystery to me.

I hope you dont mind me submitting requests. Feel free to reject them if they dont fit your aims.

Tomorrow I hope to be testing the front end stuff ;)

**Comment by Didldu-Florian** [comment]
No problem, thank you for your consideration.
I think soon light will come into the mysterious world.
I like your feedback anyway. It's all right and I'm happy if you like it.

**Comment by brianteeman** [comment]
I like it a LOT!!!

I always try to give feedback/code/translations on anything that I use - I always hope that more people will do that

**Comment by Didldu-Florian** [comment]
And now, that is awasome. Welcome :)
I appreciate it very much. Hope I didn't say anything wrong with my English.
I take off my hat, I would say in German. Thanks for all <3

**Comment by Didldu-Florian** [comment]
Stylepack feature on dev branche https://github.com/hr-it-solutions/DD_J_mod_gmaps_module/pull/35
You can also add your custom style https://mapstyle.withgoogle.com/ if wished by placing the json to media/dd_gmaps_modules/js/styles/custom.json and selecting custom from the module params

**Comment by brianteeman** [comment]
AWESOME

**Comment by Didldu-Florian** [comment]
Do you like music? Can I invite you to visit our GEMA free music website https://www.didldu.de/ select a genre and enjoy the sound ;) in the front of Joomla <3

**Comment by Didldu-Florian** [comment]
Have a good night ;)

**Comment by BaZSeE89** [comment]
Hy! I just started using, this component, and it's great! It do everything, what I need. Just one thing what will be good: In category view near the title show the number of locations in that category.
Thank you!

**Comment by Didldu-Florian** [comment]
@BaZSeE89 Thanks for your feedback. Let me implement this for you within the next week ;)
