### ISSUE TITLE
categories view - count items feature

### ISSUE THREAD

**Issue by Didldu-Florian** [hr-it-solutions/DD_J_com_gmaps_locations#87]

**Comment by Didldu-Florian** [comment]
@BaZSeE89 This feature is now added to dev branche. We will merge and release v1.1.1.8 within this weekend ;) If you can't wait, feel free to install the dev branche.

**Comment by Didldu-Florian** [comment]
PS: To enable that feature go to the menu item > params > count items > and switch to show

**Comment by BaZSeE89** [comment]
THX! It's great!
